[package]
name = "panamax"
version = "1.2.0"
edition = "2024"

[dependencies]
arrow = { version = "58.0.0", features = [
  "csv",
  "json",
  "ipc",
  "ipc_compression",
  "prettyprint",
  "chrono-tz",
  "ffi",
  "pyarrow",
  "canonical_extension_types",
  "async",
] }
assert_matches = "1.5"
async-trait = "0.1"
bindgen = "0.72"
byteorder = "1.5"
bytes = "1.11"
chrono = { version = "0.4", features = ["serde"] }
crc = "3.4"
criterion = { version = "0.8", features = ["html_reports"] }
deku = "0.20"
env_logger = "0.11"
fake = { version = "4.4", features = ["derive", "chrono", "uuid"] }
futures = "0.3"
futures-test = "0.3"
hex = "0.4"
httpmock = "0.8"
insta = { version = "1.46", features = ["json", "yaml"] }
log = "0.4"
mockall = "0.14"
mysql_async = "0.36"
nom = "8.0"
pretty_assertions = "1.4"
proptest = { version = "1.10", optional = true }
prost = "0.14"
prost-build = "0.14"
prost-types = "0.14"
quickcheck = { version = "1.1", optional = true }
quickcheck_macros = { version = "1.2", optional = true }
rand = "0.10"
rdkafka = { version = "0.39", features = ["cmake-build", "ssl", "sasl"] }
reqwest = { version = "0.13", features = ["json"] }
rkyv = "0.8.15"
rmp-serde = "1.3"
rstest = "0.26"
schema_registry_converter = { version = "4.8", features = [
  "futures",
  "proto_raw",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yml = "0.0.12"
serial_test = "3.4"
sqlx = { version = "0.8", features = [
  "runtime-tokio-rustls",
  "postgres",
  "mysql",
  "chrono",
  "uuid",
  "json",
] }
testcontainers = { version = "0.27", optional = true }
testcontainers-modules = { version = "0.15", features = [
  "kafka",
], optional = true }
thiserror = "2.0"
tokio = { version = "1.49", features = ["full"] }
tokio-postgres = "0.7"
tokio-stream = "0.1"
tokio-test = "0.4"
toml = "1.0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.21", features = ["v4", "serde"] }
wincode = { version = "0.4.5", features = [
  "std",
  "alloc",
  "derive",
  "uuid",
  "uuid-serde-compat",
] }
